In [3]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
import numpy as np
d = np.array( [0,0,0,0,0], dtype=np.int8 )
print(d, type(d), d.dtype)
print(d.shape)
print(d.itemsize)

[0 0 0 0 0] <class 'numpy.ndarray'> int8
(5,)
1


In [9]:
# create a numpy array of ones of shape (5,4)
x = np.arange(20,40)
print(x ,  len(x))
r = x.reshape(5,4)
print(r)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39] 20
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [21]:
# create a matrix of shape 4,5 with numbers from 1-21
# multiply all elements of above array by 10 .
# print odd elements from array
#  replace all even elements by their negative
a = np.arange(1,21).reshape(4,5)
print(a)
print()
print(a*100)
print()
idx = a%2 != 0
print(idx)
print()
print(a[idx])
print()
idy = a%2 == 0
a[idy]= a[idy]*(-1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]
 [1100 1200 1300 1400 1500]
 [1600 1700 1800 1900 2000]]

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

[ 1  3  5  7  9 11 13 15 17 19]

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [38]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# - create a transpose of above matrix call it M2
# - find sum of above matrix M3 = (M1 + M2)
# - Find Transpose of M3, Call it MT1. Check if M3 == MT1
# - find diffrence of M4 = (M1 - M2)
# -Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
m1 = np.arange(1,17).reshape(4,4)
print(m1)
print()
m2 = m1.T
print(m2)
print()
m3 = m1+m2
print(m3)
print()
mt1 = m3.T
print(m3)
print()
print(mt1 == m3)
print()
m4 = m1 - m2
print(m4)
print()
mt2 = m4.T
print(mt2)
print()
print(mt2==m4)
print(mt2== -m4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [55]:
# - create a matrix (3x4) R1 of random numbers between 10-40
# - find min and max column wise
# - replace the last column with sum of all the columns
r1= np.random.randint(10,40 , size=(3,4))
print(r1)
print(r1.min(axis = 1),r1.max(axis = 1))

print()
column = r1[: , 3]
print(column)


[[16 38 38 20]
 [21 33 39 20]
 [17 22 39 25]]
[16 20 17] [38 39 39]

[20 20 25]


In [34]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1
import numpy as np
r1  = np.random.randint(10,40, size=(3,4))
print(r1)
print()
r2 = r1 % 2 == 0
print()
print(r2)



w = np.where(r2, 'nan' , r1)
print()
print(w)
print()


[[15 31 34 14]
 [14 21 39 31]
 [35 31 15 20]]


[[False False  True  True]
 [ True False False False]
 [False False False  True]]

[['15' '31' 'nan' 'nan']
 ['nan' '21' '39' '31']
 ['35' '31' '15' 'nan']]



In [39]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
print()
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)


[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
