In [ ]:
# What is numpy?
# Why numpy?

In [ ]:
# c-array vs python list
# c 
# - size of data type is fixed ex: int=>4 bytes
# - array elements are  of same type

# a = [10,20]
# a: 0x1100
#     [ 10, 20, 30]
#    10 : 0x1100
#    20 : 0x1104

# python
# - types don't have a fixed size
# - list elements can be of different type

a = [ 10, "abcd"]
# a:0x1000  
#   [ 0x1100,  0x1200 ]

# 0x1100 10
# 0x1200 "abcd"

In [2]:
# imports go here
import numpy as np

In [3]:
# what's inside numpy module
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [ ]:
# ndarray
# n dimensional array :vectors, matrices.. or even higher dimensional data

In [23]:
# numpy int and float types
i = np.int8()
print(i, type(i))
i = np.int8(19)
print(i, type(i))
i = np.int8(127)
print(i, type(i))
i = np.int8(128)
print(i, type(i))
i = np.int8(1000)
print(i, type(i))

print()
i = np.int16(1000)
print(i, type(i))
i = np.int16(40000)
print(i, type(i))

print()
i = np.int32(40000)
print(i, type(i))
i = np.int32(2000000000)
print(i, type(i))
i = np.int64(4000000000)
print(i, type(i))

0 <class 'numpy.int8'>
19 <class 'numpy.int8'>
127 <class 'numpy.int8'>
-128 <class 'numpy.int8'>
-24 <class 'numpy.int8'>

1000 <class 'numpy.int16'>
-25536 <class 'numpy.int16'>

40000 <class 'numpy.int32'>
2000000000 <class 'numpy.int32'>
4000000000 <class 'numpy.int64'>


In [25]:
d = np.array( [] )
print(d, type(d))

[] <class 'numpy.ndarray'>


In [30]:
d = np.array( [10,200], dtype=np.int8 )
print(d, type(d), d.dtype)

[ 10 -56] <class 'numpy.ndarray'> int8


In [31]:
d = np.array( [10,200] )
print(d, type(d), d.dtype)

[ 10 200] <class 'numpy.ndarray'> int32


In [32]:
d = np.array( [10,200, 4000000000] )
print(d, type(d), d.dtype)

[        10        200 4000000000] <class 'numpy.ndarray'> int64


In [42]:
d = np.array( [10,200, 4000000000], dtype='float64' )
print(d, type(d), d.dtype)

# 4000 = 4*(10^3)
# 4e+3

# 0.0004 = 4.0 * (10^-4)
# 4e-4

[1.e+01 2.e+02 4.e+09] <class 'numpy.ndarray'> float64


In [41]:
d = np.array( [10,200, 400000000000000000000000000000000000000000000000000000000]  )
print(d, type(d), d.dtype)

[10 200 400000000000000000000000000000000000000000000000000000000] <class 'numpy.ndarray'> object


In [43]:
d = np.array( [10,200, 4.1])
print(d, d.dtype)

[ 10.  200.    4.1] float64


In [44]:
d = np.array( [10,200, 4.1, "abcd"])
print(d, d.dtype)b


['10' '200' '4.1' 'abcd'] <U32


In [57]:
d = np.array( ["abcd", "ab", "123456"])
print(d, d.dtype)

print(d.dtype)
print(d.shape)
print(d.size)
print(d.T.shape)

['abcd' 'ab' '123456'] <U6
<U6
(3,)
3
(3,)


In [7]:
# What's a scalar, vector and matrix
print(10) # scalar
print( [10,203,40,50 ]) # vector :1-d array

a = [[1,2,3],
     [4,5,6]]
print(  a ) # marix : 2-d array
print(a[1][2])


10
[10, 203, 40, 50]
[[1, 2, 3], [4, 5, 6]]
6


In [65]:
# ndarray type and array function
a = np.array([ [1,2,3], [4,5,6]])
print(a, type(a))
print("type", a.dtype)
print("shape", a.shape)
print("size", a.size)
print("ndim", a.ndim)
print(a.T) # Transpose

print()
a = np.array([ [1],[2],[3]])
print(a, a.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
type int32
shape (2, 3)
size 6
ndim 2
[[1 4]
 [2 5]
 [3 6]]

[[1]
 [2]
 [3]] (3, 1)


In [66]:
# 2d arrays/ matrices
mat1 = np.array( [
    [10,20,30], 
    [60,50,40],
])

In [70]:
# customizing data types of arrays
print(mat1.dtype)
r = mat1.astype("float32")
print(r)
print(mat1)

int32
[[10. 20. 30.]
 [60. 50. 40.]]
[[10 20 30]
 [60 50 40]]


In [71]:
# narray attributes: dtype, size, shape, T, itemsize, ndim
# itemsize tell size of an item of an element in num of bytes
# itemsize is dependent on dtype/data type

In [86]:
# nan and operations on nan with scalar
print(np.nan)
print(type(np.nan))

print(np.nan + np.nan)
print(np.nan + 1)
print(np.nan + 1 * 20)
print(np.nan > 1)
print(np.nan < 1)
print(np.nan == np.nan)
print(np.nan != np.nan)
print(np.nan and np.int(1))

nan
<class 'float'>
nan
nan
nan
False
False
False
True
1


In [ ]:
# creating numpy arrays: ones, zeros, arange, linspace


In [ ]:
# reshaping and resizing

In [ ]:
# indexing

In [ ]:
# slicing

In [ ]:
# updating data via indexing and slicing

In [ ]:
# indexing via lists

In [ ]:
# boolean indexing and updating values

In [ ]:
# arithmetic and broadcasting

In [ ]:
# logical operations: &, | , ~

In [ ]:
# Exercise:
# given below a 2-darray 'mat'. 
# Replace all even values with square and odd values with their half
mat = np.arange(10,22).reshape(3,4)
print(mat)

In [ ]:
# generating random numbers

In [ ]:
# aggregate operations

In [ ]:
# aggregate functions with Nan data

In [ ]:
# checking nans: np.isna()

In [ ]:
# any, all

In [ ]:
# using where

# where (bools, scalar, scalar)

# where (bools, mat, scalar)

# where (bools, scalar, mat)

In [ ]:
# Exercise:
# given below a 2-darray 'mat'. 
# Create a new matrix which contains all even values from mat as it is
# but odd values reduced to their half (as integers)
mat = np.arange(10,22).reshape(3,4)
print(mat)