In [ ]:
# What is numpy?
# Why numpy?

In [ ]:
# c-array vs python list
# c 
# - size of data type is fixed ex: int=>4 bytes
# - array elements are  of same type

# a = [10,20]
# a: 0x1100
#     [ 10, 20, 30]
#    10 : 0x1100
#    20 : 0x1104

# python
# - types don't have a fixed size
# - list elements can be of different type

a = [ 10, "abcd"]
# a:0x1000  
#   [ 0x1100,  0x1200 ]

# 0x1100 10
# 0x1200 "abcd"

In [2]:
# imports go here
import numpy as np

In [3]:
# what's inside numpy module
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [ ]:
# ndarray
# n dimensional array :vectors, matrices.. or even higher dimensional data

In [23]:
# numpy int and float types
i = np.int8()
print(i, type(i))
i = np.int8(19)
print(i, type(i))
i = np.int8(127)
print(i, type(i))
i = np.int8(128)
print(i, type(i))
i = np.int8(1000)
print(i, type(i))

print()
i = np.int16(1000)
print(i, type(i))
i = np.int16(40000)
print(i, type(i))

print()
i = np.int32(40000)
print(i, type(i))
i = np.int32(2000000000)
print(i, type(i))
i = np.int64(4000000000)
print(i, type(i))

0 <class 'numpy.int8'>
19 <class 'numpy.int8'>
127 <class 'numpy.int8'>
-128 <class 'numpy.int8'>
-24 <class 'numpy.int8'>

1000 <class 'numpy.int16'>
-25536 <class 'numpy.int16'>

40000 <class 'numpy.int32'>
2000000000 <class 'numpy.int32'>
4000000000 <class 'numpy.int64'>


In [25]:
d = np.array( [] )
print(d, type(d))

[] <class 'numpy.ndarray'>


In [30]:
d = np.array( [10,200], dtype=np.int8 )
print(d, type(d), d.dtype)

[ 10 -56] <class 'numpy.ndarray'> int8


In [31]:
d = np.array( [10,200] )
print(d, type(d), d.dtype)

[ 10 200] <class 'numpy.ndarray'> int32


In [32]:
d = np.array( [10,200, 4000000000] )
print(d, type(d), d.dtype)

[        10        200 4000000000] <class 'numpy.ndarray'> int64


In [42]:
d = np.array( [10,200, 4000000000], dtype='float64' )
print(d, type(d), d.dtype)

# 4000 = 4*(10^3)
# 4e+3

# 0.0004 = 4.0 * (10^-4)
# 4e-4

[1.e+01 2.e+02 4.e+09] <class 'numpy.ndarray'> float64


In [41]:
d = np.array( [10,200, 400000000000000000000000000000000000000000000000000000000]  )
print(d, type(d), d.dtype)

[10 200 400000000000000000000000000000000000000000000000000000000] <class 'numpy.ndarray'> object


In [43]:
d = np.array( [10,200, 4.1])
print(d, d.dtype)

[ 10.  200.    4.1] float64


In [44]:
d = np.array( [10,200, 4.1, "abcd"])
print(d, d.dtype)b


['10' '200' '4.1' 'abcd'] <U32


In [57]:
d = np.array( ["abcd", "ab", "123456"])
print(d, d.dtype)

print(d.dtype)
print(d.shape)
print(d.size)
print(d.T.shape)

['abcd' 'ab' '123456'] <U6
<U6
(3,)
3
(3,)


In [7]:
# What's a scalar, vector and matrix
print(10) # scalar
print( [10,203,40,50 ]) # vector :1-d array

a = [[1,2,3],
     [4,5,6]]
print(  a ) # marix : 2-d array
print(a[1][2])


10
[10, 203, 40, 50]
[[1, 2, 3], [4, 5, 6]]
6


In [65]:
# ndarray type and array function
a = np.array([ [1,2,3], [4,5,6]])
print(a, type(a))
print("type", a.dtype)
print("shape", a.shape)
print("size", a.size)
print("ndim", a.ndim)
print(a.T) # Transpose

print()
a = np.array([ [1],[2],[3]])
print(a, a.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
type int32
shape (2, 3)
size 6
ndim 2
[[1 4]
 [2 5]
 [3 6]]

[[1]
 [2]
 [3]] (3, 1)


In [66]:
# 2d arrays/ matrices
mat1 = np.array( [
    [10,20,30], 
    [60,50,40],
])

In [70]:
# customizing data types of arrays
print(mat1.dtype)
r = mat1.astype("float32")
print(r)
print(mat1)

int32
[[10. 20. 30.]
 [60. 50. 40.]]
[[10 20 30]
 [60 50 40]]


In [71]:
# narray attributes: dtype, size, shape, T, itemsize, ndim
# itemsize tell size of an item of an element in num of bytes
# itemsize is dependent on dtype/data type

In [86]:
# nan and operations on nan with scalar
print(np.nan)
print(type(np.nan))

print(np.nan + np.nan)
print(np.nan + 1)
print(np.nan + 1 * 20)
print(np.nan > 1)
print(np.nan < 1)
print(np.nan == np.nan)
print(np.nan != np.nan)
print(np.nan and np.int(1))

nan
<class 'float'>
nan
nan
nan
False
False
False
True
1


In [6]:
# creating numpy arrays: ones, zeros, arange, linspace
print(np.zeros(10))
print()
print(np.zeros((3,2)))
print()
print(np.zeros((3,2,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [12]:
# arange generates an array, which is  different from python range function
print(np.arange(10))
print(np.arange(10,20))
print(np.arange(10,20,2, dtype="float"))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10. 12. 14. 16. 18.]


In [16]:
# linspace generates  step based on no. of elements
print(np.linspace(10,20, 6)) # linear space:6 here is no. of elements

[10. 12. 14. 16. 18. 20.]


In [ ]:
# reshaping and resizing

In [20]:
# reshape: doesn't alter  memory
a = np.arange(10,22)
print(a, len(a))

r=a.reshape(3,4)
print(r) # 'r' is a view of 'a'
print()
print(a)

r=a.reshape(4,4) # this fails as a has  only 16 elements

[10 11 12 13 14 15 16 17 18 19 20 21] 12
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[10 11 12 13 14 15 16 17 18 19 20 21]


ValueError: cannot reshape array of size 12 into shape (4,4)

In [23]:
# resize: alters  memory
a = np.arange(10,22)
print(a, len(a))

r=a.resize(3,4) # modifies original
print(r) # 'r' is None
print()
print(a)

a.resize(4,2)
print()
print(a)

a.resize(4,5)
print()
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21] 12
None

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]]

[[10 11 12 13 14]
 [15 16 17  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [27]:
# indexing
a = np.arange(10,22).reshape(3,4)
print(a)

print()
print(a[1])
print()
print(a[1,3])

print()
print(a[1,-3])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[14 15 16 17]

17

15


In [151]:
# slicing
print(a)
print()
print(a[1:3]) # row, col
print()
print(a[:2])
print()
print(a[:,1:3])
print()
print(a[:,1])
print()
print(a[1,::-1])
print()
print(a[1,::-1][1:2])

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

[11, 12]

[10, 11]



TypeError: list indices must be integers or slices, not tuple

In [39]:
print(a[:,1])

print()
print(a[:,1:2])

[11 15 19]

[[11]
 [15]
 [19]]


In [52]:
# updating data via indexing and slicing
a = np.arange(10,22).reshape(3,4)
print(a)

print()
a[1,1] = 100
print(a)

print()
a[1,:] = 100 # assign scalar to slice
print(a)

print()
a2 = np.arange(4)
a[1] = a2 # assign array a2  (size4)  to row[1] (size 4) 
print(a)

a[:,1] = a2 # assign array a2  (size4)  to col[1] (size 3) 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[ 10  11  12  13]
 [ 14 100  16  17]
 [ 18  19  20  21]]

[[ 10  11  12  13]
 [100 100 100 100]
 [ 18  19  20  21]]

[[10 11 12 13]
 [ 0  1  2  3]
 [18 19 20 21]]


ValueError: could not broadcast input array from shape (4) into shape (3)

In [ ]:
import copy 
class Mat:
    def __init__(self, seq, copy=True):
        self.__mat = copy.deepcopy(seq)
        
    def reshape(self, size):
        if size == len(self.__mat):
            return Mat(self.__mat, copy=False)
        
        if size > len(self.__mat):
            self.__mat.append(0)
            ret
            
        if size < len(self.__mat):
            
        

In [146]:
a = np.arange(10,22)
print(a)
a1 = a.reshape(3,4) # a1 is a view, not  copy
a2 = a.reshape(4,3) # a1 is a view, not  copy

#a1.resize(2,3)
a.resize(2,2)

[10 11 12 13 14 15 16 17 18 19 20 21]


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [71]:
# indexing via lists
a = np.arange(10,22).reshape(3,4)
print(a)

print()
print(a[ [0,2] ])

print()
print(a[ (2,0,1), ])

print()
print(a[ (2,0,1), 1 ])

print()
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[10 11 12 13]
 [18 19 20 21]]

[[18 19 20 21]
 [10 11 12 13]
 [14 15 16 17]]

[19 11 15]

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [72]:
# generating random numbers

print(dir(np.random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


In [80]:
r = np.random.randn(10) # picks 10 nums from std. normal dist.
print(r)

[-0.1733578   0.24373781 -0.03068834  2.1057976  -1.26625619 -0.91928817
 -0.21827554 -1.20078845  0.57925568 -0.44031686]


In [86]:
r  = np.random.randint(20) # 0-19
print(r)
r  = np.random.randint(20,30) # 0-19
print(r)
r  = np.random.randint(20,30, size=(3,2))
print(r)

14
29
[[20 27]
 [29 26]
 [28 25]]


In [90]:
# logical ops
r  = np.random.randint(1,10, size=(3,4))
print(r)


[[4 6 6 9]
 [6 4 9 8]
 [8 7 7 8]]


In [100]:
# no. > 5
a = r > 5
print(a)

# no. between 4-8

print()
a =  (r >= 4) & (r <= 8)
print(a)

print()
print( r % 2 == 0)

[[ True  True False  True]
 [False False False False]
 [ True  True  True False]]

[[ True False False  True]
 [False False False False]
 [ True  True  True False]]

[[ True False False  True]
 [ True  True False  True]
 [ True False False False]]


In [101]:
# boolean indexing and updating values
r  = np.random.randint(1,10, size=(3,4))
print(r)

idx = r % 2 == 0
print()
print(idx)

print()
print(r[idx])

[[8 2 3 5]
 [5 8 5 2]
 [5 5 5 7]]

[[ True  True False False]
 [False  True False  True]
 [False False False False]]

[8 2 8 2]


In [58]:
# arithmetic and broadcasting

a = np.arange(10,22).reshape(3,4)
print(a)

print()
print(a + 100)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[110 111 112 113]
 [114 115 116 117]
 [118 119 120 121]]


In [59]:
a = np.arange(10,22).reshape(3,4)
print(a)

print()
a2 = np.arange(4)
print(a2)

# add to rows
print()
r = a + a2
print(r)

print()
a3 = np.arange(3)
print(a3)

# add to cols
print()
r = a.T + a3
print(r.T)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[0 1 2 3]

[[10 12 14 16]
 [14 16 18 20]
 [18 20 22 24]]

[0 1 2]

[[10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]


In [102]:
# logical operations: &, | , ~
r  = np.random.randint(1,10, size=(3,4))
print(r)

idx = r % 2 == 0
print()
print(idx)
print(~idx)

print()
print(r[~idx])

[[6 8 4 4]
 [4 4 1 9]
 [4 8 5 3]]

[[ True  True  True  True]
 [ True  True False False]
 [ True  True False False]]
[[False False False False]
 [False False  True  True]
 [False False  True  True]]

[1 9 5 3]


In [108]:
# Exercise:
# given below a 2-darray 'mat'. 
# Replace all even values with square and odd values with their half
mat = np.arange(10,22).reshape(3,4)
print(mat)

e = mat%2 ==  0
mat[e] = mat[e] **2
mat[~e] = mat[~e] / 2

# print(mat[~e] / 2)
print()
print(mat)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[100   5 144   6]
 [196   7 256   8]
 [324   9 400  10]]


In [114]:
# aggregate operations
mat = np.arange(10,22).reshape(3,4)
print(mat)

print()
print(mat.sum())

print()
print(mat.sum(axis=0))

print()
print(mat.sum(axis=1))

print()
print(mat.min(axis=0))

print()
print(mat.mean(axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

186

[42 45 48 51]

[46 62 78]

[10 11 12 13]

[14. 15. 16. 17.]


In [116]:
# aggregate functions with Nan data
# aggregate operations
mat = np.arange(10,22, dtype="float").reshape(3,4)
mat[0,0] = np.nan
print(mat)

print()
print(mat.sum())

print()
print(mat.sum(axis=0))

print()
print(mat.sum(axis=1))

print()
print(mat.min(axis=0))

print()
print(mat.mean(axis=0))

[[nan 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]

nan

[nan 45. 48. 51.]

[nan 62. 78.]

[nan 11. 12. 13.]

[nan 15. 16. 17.]


In [128]:
# checking nans: np.isna()

mat = np.arange(10,22, dtype="float").reshape(3,4)
mat[ [1,2,1],[0,1,2] ] = np.nan # mapping of rows and columns
print(mat)

print()
print(mat == np.nan)

print()
print(np.isnan(mat))

print()
print(mat[~np.isnan(mat)].sum())

[[10. 11. 12. 13.]
 [nan 15. nan 17.]
 [18. nan 20. 21.]]

[[False False False False]
 [False False False False]
 [False False False False]]

[[False False False False]
 [ True False  True False]
 [False  True False False]]

137.0


In [131]:
# any, all
mat = np.arange(10,22, dtype="float").reshape(3,4)
print(mat)

print()
print(mat.any())
print(mat.all())

print()
r = mat%2 == 0
print(r.any())
print(r.all()) # any([1 2])

[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]

True
True

True
False


In [154]:
# using where
mat = np.arange(10,22).reshape(3,4)
print(mat)

r = mat % 2 == 0
print()
print(r)

w = np.where(r)
print()
print(w)

# where (bools, scalar, scalar)
w = np.where(r, "even", "odd")
print()
print(w)

# where (bools, mat, scalar)
w = np.where(r, mat, "odd")
print()
print(w)

w = np.where(r, mat, 1)
print()
print(w)


w = np.where(r, mat, 1.5)
print()
print(w)

# where (bools, scalar, mat)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]

(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 2, 0, 2], dtype=int64))

[['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']]

[['10' 'odd' '12' 'odd']
 ['14' 'odd' '16' 'odd']
 ['18' 'odd' '20' 'odd']]

[[10  1 12  1]
 [14  1 16  1]
 [18  1 20  1]]

[[10.   1.5 12.   1.5]
 [14.   1.5 16.   1.5]
 [18.   1.5 20.   1.5]]


In [ ]:
# Exercise:
# given below a 2-darray 'mat'. 
# Create a new matrix which contains all even values from mat as it is
# but odd values reduced to their half (as integers)
mat = np.arange(10,22).reshape(3,4)
print(mat)