In [1]:
import numpy as np

In [7]:
##- create a numpy array of 5 zeros.
ze=np.zeros(5)
print(ze)
##- check datatype, itemsize and shape of above
print('Datatype: ', ze.dtype)
print('Item Size:', ze.itemsize)
print('Shape: ', ze.shape)

[0. 0. 0. 0. 0.]
Datatype:  float64
Item Size: 8
Shape:  (5,)


In [9]:
###- create a numpy array of ones of shape (5,4)
arr = np.ones((5,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
###- create a matrix of shape 4,5 with numbers from 1-20
arr = np.arange(1,21)
arr.resize(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
###- multiply all elements of above array by 10
arr1 = arr*10
print(arr1)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [13]:
###- print odd elements from array
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [24]:
###- replace all even elements by their negative
print(arr)
c = arr%2==0
arr3 = np.where(c, -arr, arr)
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [11]:
''' create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2'''

M1 = np.linspace(1,16,16).reshape(4,4)
print(M1)
M2 = M1.T
print(M2)

M3 = M1+M2
print(M3)

MT1 = M3.T
if(M3==MT1).all:
    print('Matrix Equal')
else:
    print('Matrix different')
    
M4 = M1 - M2
print(M4)
MT2 = M4.T
print(MT2)

if(M4==MT2).all:
    print('Matrix Equal')
else:
    print('Matrix different')
    
if(M4==-MT2).all:
    print('Matrix Equal')
else:
    print('Matrix different')

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]
Matrix Equal
[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]
[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]
Matrix Equal
Matrix Equal


In [24]:
'''- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns'''

ran=np.random.randint(10,40,(3,4))
print(ran)

print(ran.min(axis=0))
print(ran.max(axis=0))

#ran = ran[]
#print(dir(np.random))

[[14 19 22 20]
 [10 25 27 20]
 [10 26 10 13]]
[10 19 10 13]
[14 26 27 20]


In [34]:
'''- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1'''

R1 = np.random.randint(10,40, (3,4)).astype('float32')
R1[R1%2==0] = np.nan
print(R1)
print(R1[~np.isnan(R1)].sum())

[[29. 25. nan 27.]
 [13. 35. nan 29.]
 [nan 23. 15. 17.]]
213.0


In [25]:
'''- check output of this code ''' 
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)



[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
