In [3]:
import numpy as np

d = np.array([10,20])
print(d,type(d),d.dtype)

d = np.array([10,20],dtype=np.int8)
print(d,type(d),d.dtype)

[10 20] <class 'numpy.ndarray'> int64
[10 20] <class 'numpy.ndarray'> int8


In [7]:
import numpy as np

d = np.array([10,200000000000000000000000000000000000000000])
print(d[1]*15)
print(d,type(d),d.dtype)

3000000000000000000000000000000000000000000
[10 200000000000000000000000000000000000000000] <class 'numpy.ndarray'> object


In [11]:
import numpy as np

d = np.array(["10","20000000000000000000000000000000000000000000000000000000000000000000000000000000000"])
print(d,type(d),d.dtype)

['10'
 '20000000000000000000000000000000000000000000000000000000000000000000000000000000000'] <class 'numpy.ndarray'> <U83


In [26]:
import numpy as np

d = np.array([[10,20],[15,20],[11,12]])
print(d.shape)
print(d.size)
print(d.T)
print(d.ndim)
print(d.itemsize)








(3, 2)
6
[[10 15 11]
 [20 20 12]]
2
8


In [33]:
import numpy as np

d = np.array([[10,20,15],[20,11,12]])
print(d.shape)
print(d.size)
print(d.T)
print(d.ndim)
print(d.itemsize)


f = d.astype(np.float64)
print(f.shape)
print(f.size)
print(f.T)
print(f.ndim)
print(f.itemsize)

(2, 3)
6
[[10 20]
 [20 11]
 [15 12]]
2
8
(2, 3)
6
[[10. 20.]
 [20. 11.]
 [15. 12.]]
2
8


<h1>adfadfa</h1>







In [36]:
import numpy as np

print(np.zeros(5))
print(np.zeros([5,3]))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
print(np.arange(10))
print(np.arange(10,20))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [42]:
print(np.linspace(10,19,10))

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [53]:
a =np.arange(10,22)
print(a)
b = a.reshape(3,4)
print(b)
c = b.reshape(4,3)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [ ]:
#resize alters memory

In [60]:
c= [[1,2,3][1,2,2]]
c.resize(12)
print(c)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-60-631fd6f0af57>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  c= [[1,2,3][1,2,2]]


TypeError: list indices must be integers or slices, not tuple

In [80]:
# Exercise:
# given below a 2-darray 'mat'. 
# Replace all even values with square and odd values with their half
mat = np.arange(10,22).reshape(3,4)
print(mat)

e = mat%2 == 0
mat[e] = mat[e]**2
print(mat)
mat[~e] = mat[~e]/2
print(mat)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[100  11 144  13]
 [196  15 256  17]
 [324  19 400  21]]
[[100   5 144   6]
 [196   7 256   8]
 [324   9 400  10]]


In [87]:
mat = np.arange(10,22).reshape(3,4)
print(mat)
print(mat.sum())

print(mat.sum(axis=0))
print(mat.min(axis=0))
print(mat.max(axis=0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
186
[42 45 48 51]
[10 11 12 13]
[18 19 20 21]


In [88]:
# using where
mat = np.arange(10,22).reshape(3,4)
print(mat)

r = mat % 2 == 0
print()
print(r)

w = np.where(r)
print()
print(w)

# where (bools, scalar, scalar)
w = np.where(r, "even", "odd")
print()
print(w)

# where (bools, mat, scalar)
w = np.where(r, mat, "odd")
print()
print(w)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))

[['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']]

[['10' 'odd' '12' 'odd']
 ['14' 'odd' '16' 'odd']
 ['18' 'odd' '20' 'odd']]


In [93]:
# Exercise:
# given below a 2-darray 'mat'. 
# Create a new matrix which contains all even values from mat as it is
# but odd values reduced to their half (as integers)
mat = np.arange(10,22).reshape(3,4)
r = mat % 2 == 0
mat = np.where(r,mat,mat//2)

print(mat)

[[10  5 12  6]
 [14  7 16  8]
 [18  9 20 10]]


In [111]:
 a = np.arange(10,22)
print(a)
a1 = a.reshape(3,4)
print(a1)
a.resize(1,12)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 11 12 13 14 15 16 17 18 19 20 21]]


In [113]:
 a = np.arange(10,22).reshape(3,2,2)
print(a)

[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]

 [[18 19]
  [20 21]]]
