In [1]:
#1. Convert Tuples to List
t=(1,2,3,4,5)
print(list(t))

[1, 2, 3, 4, 5]


In [13]:
#2. WAp to join List and Tuple
l=[1,3,5,7]
l1=l.copy()
t=(8,6,4,2)
l.append(t) ##add tuple to list
l1.extend(t) ## add tuple value as seperate item in list
la=l
le=l1
print(la,le)

[1, 3, 5, 7, (8, 6, 4, 2)] [1, 3, 5, 7, 8, 6, 4, 2]


In [5]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [15]:
#3.difference between list and type

#a. list uses [], tuple uses ()
#b. list are mutable but tuples are immutable



In [23]:
#4. Reverse the list
l=['a','d','c','A','C']
l.sort(reverse=True)
print(l)

['d', 'c', 'a', 'C', 'A']


In [25]:
#5. print elements at Odd index
l=[10,11,20,21,30,31,40,41]
s=l[1:len(l):2]
print(s)

[11, 21, 31, 41]


In [26]:
#6 Deep Copy aand Shallow Copy


In [27]:
#7 Predict Output
n_list = ["Happy",[2,0,1,5]]
print(n_list[0][1])
print(n_list[1][3])
#predicted output
#a
#5

a
5


In [28]:
#8 Predict Output
odd=[2,4,6,8]
odd[0]=1
print(odd)
odd[1:4]=[3,5,7]
print(odd)
#predicted output
#[1,4,6,8]
#[1,3,5,7]

[1, 4, 6, 8]
[1, 3, 5, 7]


In [29]:
#9 Predict Output
odd=[1,3,5]
odd.append([7,9])
print(odd)
odd.extend([11,13])
print(odd)
#preditced output
#[1,3,5,[7,9]]
#[1,3,5,[7,9],11,13]

[1, 3, 5, [7, 9]]
[1, 3, 5, [7, 9], 11, 13]


In [30]:
x=1,2,3
print(type(x))
x=(1)
print(type(x))
x=1
print(type(x))
x=1,
print(type(x))
#predicted output
#tuple
#int
#int
#tuple

<class 'tuple'>
<class 'int'>
<class 'int'>
<class 'tuple'>


In [35]:
#11 
from numpy import matrix
a=matrix([[1,2,3], [4,5,6], [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
#12 predict output
t=tuple('String')
print(t)
print(t[::-1])
print(t[::2][::-2])
#predicted output
#('S','t','r','i','n','g')
#('g','n','i','r','t','S')
#('n','S')

('S', 't', 'r', 'i', 'n', 'g')
('g', 'n', 'i', 'r', 't', 'S')
('n', 'S')


In [37]:
#13 predict output
t=tuple([10,20,30,40,50,60])
print(60 in t)
print('60' in t)
print(t.count(10))
print(t.index(40))
#predicted output
#True
#False
#1
#3

True
False
1
3


In [3]:
#14 Palindrome
s=list(input('Enter a String :\t'))
d=s.copy()
s.reverse()
if str(d).upper()==str(s).upper():
    print('String Palindrome')
else:
    print('Not a Palindrome')

Enter a String :	Malayalam
String Palindrome


In [19]:
#15
s=[]
for a in range(1,5):
    a=a*5
    s.append((a))
    s.sort(reverse=True)
print(tuple(s))


(20, 15, 10, 5)


In [20]:
#16
s=input('Enter a String :\t')
print(list(s))

Enter a String :	All is Well
['A', 'l', 'l', ' ', 'i', 's', ' ', 'W', 'e', 'l', 'l']


In [22]:
#17
print('1 2'.split())
print([1,3,2].sort())
print('abc'.upper())
print(1 in [1,2])
#predicted output
#List
#None
#Str
#Boolean

['1', '2']
None
ABC
True
