## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

In [2]:
#1. create a numpy array of 5 zero
a=np.zeros(5)
print(a,type(a),a.dtype,a.itemsize,a.shape)

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'> float64 8 (5,)


In [5]:
#2. create a numpy array of ones of shape (5,4)
a1=np.ones((5,4))
print(a1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#3. create a matrix of shape 4,5 with numbers from 1-20
a2=np.arange(1,21).reshape(4,5)
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
#4.multiply all elements of above array by 10
a3=a2*10
print(a3)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [21]:
#5. print odd elements from array
a=np.random.randint(1,11,size=(4,4))
print(a)
idx= a%2 !=0
print(a[idx])

[[ 5  9  4  4]
 [ 5  4  5  1]
 [ 5  1  5  6]
 [ 1  5  4 10]]
[5 9 5 5 1 5 1 5 1 5]


In [22]:
#6. replace all even elements by their negative
print(a)
print()
print(a[~idx]*-1)

[[ 5  9  4  4]
 [ 5  4  5  1]
 [ 5  1  5  6]
 [ 1  5  4 10]]

[ -4  -4  -4  -6  -4 -10]


In [34]:
##7
'''- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2'''

M1=np.arange(1,17).reshape(4,4)
print(M1)
M2= M1.T
print()
print(M2)
M3=M1+M2
print()
print(M3)
MT1 = M3.T
print()
print(MT1)
a=M3 == MT1
if a.all():
    print('Both M3 and MT1 is same')
else:
    print('Both M3 and MT1 is not same')
M4=M1-M2
print()
print(M4)
MT2 = M4.T
print()
print(MT1)
b=M4 == MT2
if b.all():
    print('Both M4 and MT2 is same')
else:
    print('Both M4 and MT2 is not same')
c=M4 == -MT2
if c.all():
    print('Both M4 and -MT2 is same')
else:
    print('Both M4 and -MT2 is not same')
    

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
Both M3 and MT1 is same

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
Both M4 and MT2 is not same
Both M4 and -MT2 is same


In [38]:
##8.
'''- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns'''
R1=np.random.randint(10,40,size=(3,4))
print(R1)
print(R1.min(axis=0))
print(R1.max(axis=0))
R1[:,3]= R1.sum(axis=1)
print(R1)

[[10 39 32 31]
 [17 20 37 32]
 [32 14 11 35]]
[10 14 11 31]
[32 39 37 35]
[[ 10  39  32 112]
 [ 17  20  37 106]
 [ 32  14  11  92]]


In [44]:
##9.
'''- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1'''
R1=np.random.randint(10,40,size=(3,4))
print(R1)
r=R1%2 ==0
w=np.where(r,np.nan,R1)
print(w)
print(np.isnan(w).sum())


[[25 28 30 13]
 [22 11 35 11]
 [36 11 23 24]]
[[25. nan nan 13.]
 [nan 11. 35. 11.]
 [nan 11. 23. nan]]
5


In [47]:
##10.

'''- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`'''
#[[1 2 3]
# [4 5 6]
#  [7 8 9]]

#[[11 12 13]
# [14 15 16]
# [17 18 19]]

a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
