## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [27]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

import numpy as np
#d=np.array([0,0,0,0,0])
d=np.zeros(5)
print(d)
print("datatype of d:", type(d))    # type(d) gives datatype of 'd'
print("datatype of array elements:" ,d.dtype)  # dtype gives datatype of d elements means array elements datatype
print("itemsize:" ,d.itemsize)  # size of item of array
print("shape:", d.shape)  # row, col

[0. 0. 0. 0. 0.]
datatype of d: <class 'numpy.ndarray'>
datatype of array elements: float64
itemsize: 8
shape: (5,)


In [29]:
# create a numpy array of ones of shape (5,4)

d=np.ones((5,4))
print(d)
print(d.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


In [32]:
# create a matrix of shape 4,5 with numbers from 1-20

d=np.arange(1,21)
print(d)
r=d.reshape(4,5)
print(r)
print()
a=np.arange(1,21).reshape(4,5)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
# multiply all elements of above array by 10

print(a*10)


[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [43]:
# print odd elements from array
# replace all even elements by their negative

a=np.arange(1,21).reshape(4,5)
print(a)
print(a.size)
r=a%2==0
# print(r)  # checking even values
# print(~r)  # checking odd values
print("odd elements:", a[~r])
a[r]=-a[r]
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20
odd elements: [ 1  3  5  7  9 11 13 15 17 19]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [41]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

import numpy as np
# M1=np.linspace(1,16,16)
# print(M1, len(M1))
# print(M1.shape)
# r=M1.reshape(4,4)
# print(r)

# other way
M1=np.linspace(1,16,16).reshape(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [42]:
# create a transpose of above matrix call it M2

M2=np.transpose(M1)
print(M2)
print()
#other way
print(M1.T)


[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [44]:
# find sum of above matrix M3 = (M1 + M2)
print(M1)
print(M2)
M3=M1+M2
print(M3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [51]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

MT1=np.transpose(M3)
print(MT1)
print(M3 == MT1)
M4=M1-M2
print(M4)
MT2=np.transpose(M4)
print(MT2)
print(M4==MT2)  # NOT EQUAL AS IT IS GIVING FALSE VALUES ALSO IN MATRIX
print(M4== -MT2) # EQUAL AS ALL VALUES ARE TRUE

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]
[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [38]:
#create a matrix (3x4) R1 of random numbers between 10-40

import numpy as np
import random

R1=np.random.randint(10,40,size=(3,4))
print(R1)


[[31 24 32 25]
 [20 21 35 25]
 [21 34 22 11]]


In [40]:
# find min and max column wise

R1=np.random.randint(10,40,size=(3,4))
print(R1)
print()
print("min column wise", np.min(R1,axis=0))
print("max column wise", np.max(R1, axis=0))
print()

# replace the last column with sum of all the columns

a=np.sum(R1, axis=0)
print("sum column wise", a)
print("sum of last column", a[3])
print()
R1[:,3]=a[3]
print("replaced the last column with sum of all the columns\n", R1)

[[15 35 10 19]
 [18 20 21 25]
 [29 19 38 34]]

min column wise [15 19 10 19]
max column wise [29 35 38 34]

sum column wise [62 74 69 78]
sum of last column 78

replaced the last column with sum of all the columns
 [[15 35 10 78]
 [18 20 21 78]
 [29 19 38 78]]


In [75]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

R1=np.random.randint(10,40, size=(3,4)).astype("float64")
print(R1 , R1.dtype)
print()
a=R1%2==0
R1[a]=np.nan
print(R1)
print(np.isnan(R1))
print(np.isnan(R1).sum())

[[27. 18. 17. 27.]
 [23. 17. 11. 16.]
 [39. 10. 12. 19.]] float64

[[27. nan 17. 27.]
 [23. 17. 11. nan]
 [39. nan nan 19.]]
[[False  True False False]
 [False False False  True]
 [False  True  True False]]
4


In [77]:
# check output of this code

a1 = np.arange(1,10).reshape(3,3) # create a matrix of 3*3 having random elements as an elements in the range of(1,10)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0) # axis=0 means row wise, appending row wise
print(a3)
a3 = np.append(a1,a2, axis = 1) # axis=1 means column wise, appending col wise
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
