In [1]:
import numpy as np

In [2]:
#create a numpy array of 5 zeros. check datatype, itemsize and shape 
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [3]:
#create a numpy array of ones of shape (5,4)
b = np.ones((5,4))
print(b)
print("Shape of array is:", b.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape of array is: (5, 4)


In [4]:
#create a matrix of shape 4,5 with numbers from 1-20
c= np.arange(1,21).reshape(4,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
#multiply all elements of above array by 10
print(c*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [6]:
#print odd elements from array
print(c)
print()
d = (c[c%2!=0])

print(d.reshape(2,5))




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [7]:
#replace all even elements by their negative
# where conditin
# np.where(condition,True,False)
print(c)
print()
c1 = c%2==0
print(np.where(c1,-c,c))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [8]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
N1 = np.arange(1,17).reshape(4,4)
print(N1)
print()
M1 = np.linspace(1,16,16).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [9]:
#create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [10]:
#find sum of above matrix M3 = (M1 + M2)
print(M1)
print()
print(M2)
print()
M3 = M1 + M2
print(M3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [11]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
print(M3)
print()
MT1 = M3.T
print(MT1)
print()
if (M3==MT1).all():
    print("Transpose of M3==MT1")
else:
    print("Transpose of M3!=MT1")


[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

Transpose of M3==MT1


In [12]:
#find diffrence of M4 = (M1 - M2)
print(M1)
print()
print(M2)
print()
M4 = M1 - M2
print("Answer is:", M4)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

Answer is: [[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [13]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
print(M4)
MT2 = M4.T
print()
print(MT2)
print()
print(-MT2)
if (M4 == MT2).all():
    print("M4 == MT2,its equal")
else:
    print("M4 == MT2,its not equal")
if (M4 == -MT2).all():
    print("M4 == -MT2,its equal")
else:
    print("M4 == -MT2,its not equal")

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]

[[-0. -3. -6. -9.]
 [ 3. -0. -3. -6.]
 [ 6.  3. -0. -3.]
 [ 9.  6.  3. -0.]]
M4 == MT2,its not equal
M4 == -MT2,its equal


In [14]:
#create a matrix (3x4) R1 of random numbers between 10-40
arr = np.random.randint(10,40,(3,4))
print(arr)

[[17 27 28 23]
 [22 22 38 17]
 [27 37 33 18]]


In [15]:
#find min and max column wise
print(arr.min(axis=0))
print(arr.max(axis=0))

[17 22 28 17]
[27 37 38 23]


In [16]:
#replace the last column with sum of all the columns
print(arr)
r = np.sum(arr,axis=1)
print()
print(r)

[[17 27 28 23]
 [22 22 38 17]
 [27 37 33 18]]

[ 95  99 115]


In [17]:
#create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,41,(3,4))
print(R1)

[[14 37 13 34]
 [14 22 14 37]
 [34 15 32 39]]


In [22]:
#replace all even elements with nan in R1


In [ ]:
#count number of nan in R1

In [30]:
#check output of this code
a1 = np.arange(1,10).reshape(3,3) 
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2) 
print(a3)
print()
a3 = np.append(a1,a2, axis = 0) 
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
