## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

In [2]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above

ze=np.zeros(5)
print('Array:',ze)
print('Datatype:',type(ze))
print('Itemsize:',ze.itemsize)
print('Shape:',ze.shape)

Array: [0. 0. 0. 0. 0.]
Datatype: <class 'numpy.ndarray'>
Itemsize: 8
Shape: (5,)


In [3]:
#create a numpy array of ones of shape (5,4)
one = np.ones((5,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# create a matrix of shape 4,5 with numbers from 1-20
mat=np.arange(1,21).reshape(4,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# multiply all elements of above array by 10
mat1=mat*10
print(mat1)






[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [6]:
# print odd elements from array
print(mat[mat%2!=0])


[ 1  3  5  7  9 11 13 15 17 19]


In [7]:
# replace all even elements by their negative
cond=mat%2==0
mat2=np.where(cond,-mat,mat)
print(mat2)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [8]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1=np.linspace(1,16,16).reshape(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [9]:
# create a transpose of above matrix call it M2
M2=M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [10]:
# find sum of above matrix M3 = (M1 + M2)
M3=M1+M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [11]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1=M3.T
if (MT1==M3).all:
    print(True)

True


In [12]:
# find diffrence of M4 = (M1 - M2)
M4=M1-M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [13]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2=M4.T
if (MT2==M4).all:
    print('M4 is same as MT2')
else:
    print('M4 is not same as MT2')
    
if (M4==-MT2).all:
    print('M4 is same as -MT2')
else:
    print('M4 is not same as -MT2')

M4 is same as MT2
M4 is same as -MT2


In [14]:
# create a matrix (3x4) R1 of random numbers between 10-40
ran=np.random.randint(10,40,(3,4))
print(ran)

[[10 23 25 32]
 [25 31 23 38]
 [16 37 23 23]]


In [15]:
# find min and max column wise
print(ran.min(axis=0))
print(ran.max(axis=0))

[10 23 23 23]
[25 37 25 38]


In [16]:
# replace the last column with sum of all the columns
ran[:,-1]=ran.sum(axis=1)
print(ran)

[[ 10  23  25  90]
 [ 25  31  23 117]
 [ 16  37  23  99]]


In [17]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1=np.random.randint(10,40,(3,4))
print(R1)

[[24 30 38 31]
 [19 32 36 36]
 [17 38 17 29]]


In [18]:
# replace all even elements with nan in R1
R1=R1.astype('float32')
R1[R1%2==0]=np.nan
print(R1)

[[nan nan nan 31.]
 [19. nan nan nan]
 [17. nan 17. 29.]]


In [19]:
# count number of nan in R1

print(np.count_nonzero(np.isnan(R1)))

7


In [20]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
