
# NUMPY
- create a numpy array of 5 zeros.
- check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns
- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1
- check output of this code
    a1 = np.arange(1,10).reshape(3,3)
    a2 = np.arange(11,20).reshape(3,3)
    a3 = np.append(a1,a2)
    print(a3)
    a3 = np.append(a1,a2, axis = 0)
    print(a3)
    a3 = np.append(a1,a2, axis = 1)
    print(a3)

In [4]:
import numpy as np

# create a numpy array of 5 zeros.

a = np.zeros(5)
print (a)

[0. 0. 0. 0. 0.]


In [6]:
# check datatype, itemsize and shape of above

print('Array:',a)
print('Datatype:',type(a))
print('Itemsize:',a.itemsize)
print('Shape:',a.shape)

Array: [0. 0. 0. 0. 0.]
Datatype: <class 'numpy.ndarray'>
Itemsize: 8
Shape: (5,)


In [7]:
#create a numpy array of ones of shape (5,4)

b = np.ones((5,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# create a matrix of shape 4,5 with numbers from 1-20

c = np.arange(1,21).reshape(4,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
# multiply all elements of above array by 10

d = c*10
print(d)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [10]:
# print odd elements from array

print(c[c%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [11]:
# replace all even elements by their negative

cond = c%2 == 0
e = np.where(cond,-c,c)
print(e)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [17]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.linspace(1,16,16).reshape(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [18]:
# create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [19]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [20]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
if (MT1 == M3).all:
    print(True)

True


In [21]:
# find diffrence of M4 = (M1 - M2)
M4 = M1 - M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [22]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
if (MT2 == M4).all:
    print('M4 is same as MT2')
else:
    print('M4 is not same as MT2')
    
if (M4 == -MT2).all:
    print('M4 is same as -MT2')
else:
    print('M4 is not same as -MT2')

M4 is same as MT2
M4 is same as -MT2


In [23]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,(3,4))
print(R1)

[[21 34 29 26]
 [34 17 10 35]
 [11 32 15 10]]


In [24]:
# find min and max column wise
print(R1.min(axis=0))
print(R1.max(axis=0))

[11 17 10 10]
[34 34 29 35]


In [25]:
# replace the last column with sum of all the columns
R1[:,-1] = R1.sum(axis = 1)
print(R1)

[[ 21  34  29 110]
 [ 34  17  10  96]
 [ 11  32  15  68]]


In [26]:
# create a matrix (3x4) R2 of random numbers between 10-40
R2 = np.random.randint(10,40,(3,4))
print(R2)

[[29 24 19 20]
 [34 26 14 17]
 [22 35 36 17]]


In [27]:
# replace all even elements with nan in R2
R2 = R2.astype('float32')
R2 [R2 % 2 == 0] = np.nan
print(R2)

[[29. nan 19. nan]
 [nan nan nan 17.]
 [nan 35. nan 17.]]


In [28]:
# count number of nan in R2

print(np.count_nonzero(np.isnan(R2)))

7


In [29]:
# check output of this code

a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
