# Numpy

In [3]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

import numpy as np
d = np.array([0,0,0,0,0], dtype=np.int8)
print(d, type(d), d.dtype)
print(d.shape)
print(d.itemsize)

[0 0 0 0 0] <class 'numpy.ndarray'> int8
(5,)
1


In [9]:
# create a numpy array of ones of shape (5,4)

d = np.ones((5,4))
print(d)
print(d.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


In [16]:
# create a matrix of shape 4,5 with numbers from 1-20

d = np.arange(1,21)
print(d)
r = d.reshape((4,5))
print(r)

print()
a = np.arange(1,21).reshape(4,5)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
# multiply all elements of above array by 10
print(a*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [23]:
# print odd elements from array
# replace all even elements by their negative

a = np.arange(1,21).reshape(4,5)
print(a)
print()
r = a%2 == 0
print(r)
print()
# print(r)  # checking even values
# print(~r)  # checking odd values
print("odd elements : ", a[~r])
print()
a[r] = -a[r]
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]

odd elements :  [ 1  3  5  7  9 11 13 15 17 19]

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [34]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# create a transpose of above matrix call it M2
M1 = np.linspace(1,16,16).reshape(4,4)
print(M1)
print()
M2 = np.transpose(M1)
print(M2)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [37]:
# find sum of above matrix M3 = (M1 + M2)
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
print(M1)
print(M2)
print()
M3 = (M1+M2)
print(M3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [43]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT1 = np.transpose(M3)
print(MT1)
print()
print(M3 == MT1)
print()
M4 = (M1-M2)
print(M4)
print()
MT2 = np.transpose(M4)
print(MT2)
print()
print(M4 == MT2)
print()
print(M4 == -MT2)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [76]:
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise

import numpy as np
import random

R1 = np.random.randint(10,40,size=(3,4))
print(R1)
print()
print("Min column: ", np.min(R1,axis=0))
print()
print("max column: ", np.max(R1,axis=0))

[[16 27 32 16]
 [12 26 33 16]
 [24 37 31 39]]

Min column:  [12 26 31 16]

max column:  [24 37 33 39]


In [69]:
# replace the last column with sum of all the columns

a = np.sum(R1,axis = 0)
print("sum of all columns", a)
print()
print("sum of last column", a[3])
print()
R1[:,3] = a[3]
print("replaced last column by sum of all columns\n", R1)

sum of all columns [nan 61. nan 69.]

sum of last column 69.0

replaced last column by sum of all columns
 [[15. 11. nan 69.]
 [nan 33. nan 69.]
 [11. 17. nan 69.]]


In [72]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

R1 = np.random.randint(10,40,size = (3,4)).astype("float64")
print(R1)
print()
R2 = R1%2 == 0
R1[R2] = np.nan
print(R1)
print()
print(np.isnan(R1)
print(np.isnan(R1).sum())


[[36. 17. 15. 23.]
 [25. 24. 19. 15.]
 [29. 14. 32. 17.]]

[[nan 17. 15. 23.]
 [25. nan 19. 15.]
 [29. nan nan 17.]]

4


In [74]:
# check output of this code

a1 = np.arange(1,10).reshape(3,3) # create a matrix of 3*3 having random elements as an elements in the range of(1,10)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0) # axis=0 means row wise, appending row wise
print(a3)
print()
a3 = np.append(a1,a2, axis = 1) # axis=1 means column wise, appending col wise
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
