## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [7]:
#create a numpy array of 5 zeros.
import numpy as np
arr_5=np.zeros(5)
print(arr_5.shape)
#check datatype, itemsize and shape of above
print(arr_5.dtype)
print()
print(arr_5.size)
#

(5,)
float64

5


In [8]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [16]:
#create a numpy array of ones of shape (5,4)
arr_1=np.ones(20)
print(arr_1,type(arr_1))
arr_11=arr_1.reshape(5,4)
print(arr_11)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
#create a matrix of shape 4,5 with numbers from 1-20
arr = np.arange(1,21)
print(arr)
arr_45 = arr.reshape(4,5)
print(arr_45)
#multiply all elements of above array by 10
arr_45_10 = arr_45[:,:]*10
print(arr_45_10)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [34]:
#print odd elements from array
arr_odd=(arr_45%2==0)
print(arr_odd)
print(arr_45[~arr_odd])
print()
print(arr_45[arr_odd])

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 1  3  5  7  9 11 13 15 17 19]

[ 2  4  6  8 10 12 14 16 18 20]


In [35]:
#replace all even elements by their negative
arr_45[arr_odd] = arr_45[arr_odd]*-1
print(arr_45[arr_odd])

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [41]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1=np.linspace(1,17,16).reshape(4,4)
print(M1)

[[ 1.          2.06666667  3.13333333  4.2       ]
 [ 5.26666667  6.33333333  7.4         8.46666667]
 [ 9.53333333 10.6        11.66666667 12.73333333]
 [13.8        14.86666667 15.93333333 17.        ]]


In [42]:
#create a transpose of above matrix call it M2
M2= M1.T
print(M2)

[[ 1.          5.26666667  9.53333333 13.8       ]
 [ 2.06666667  6.33333333 10.6        14.86666667]
 [ 3.13333333  7.4        11.66666667 15.93333333]
 [ 4.2         8.46666667 12.73333333 17.        ]]


In [43]:
#find sum of above matrix M3 = (M1 + M2)
M3=M1+M2
print(M3)

[[ 2.          7.33333333 12.66666667 18.        ]
 [ 7.33333333 12.66666667 18.         23.33333333]
 [12.66666667 18.         23.33333333 28.66666667]
 [18.         23.33333333 28.66666667 34.        ]]


In [47]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
idx = M3==MT1
print(MT1[idx])

[ 2.          7.33333333 12.66666667 18.          7.33333333 12.66666667
 18.         23.33333333 12.66666667 18.         23.33333333 28.66666667
 18.         23.33333333 28.66666667 34.        ]


In [54]:
#find diffrence of M4 = (M1 - M2)
M4=M1-M2
print(M4)
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2=M4.T
idx=M4==MT2
print(idx)
print(MT2[idx])
idx1=M4== -MT2
print()
print(idx1)
print(MT2[idx1])

[[ 0.  -3.2 -6.4 -9.6]
 [ 3.2  0.  -3.2 -6.4]
 [ 6.4  3.2  0.  -3.2]
 [ 9.6  6.4  3.2  0. ]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[0. 0. 0. 0.]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 0.   3.2  6.4  9.6 -3.2  0.   3.2  6.4 -6.4 -3.2  0.   3.2 -9.6 -6.4
 -3.2  0. ]


In [60]:
#create a matrix (3x4) R1 of random numbers between 10-40
R1=np.random.randint(10,30,size=(3,4))
print(R1)
#find min and max column wise
print()
print(R1.min(axis=0))
print()
print(R1.max(axis=0))

[[16 17 14 24]
 [20 27 14 29]
 [21 23 20 28]]

[16 17 14 24]

[21 27 20 29]


In [63]:
#replace the last column with sum of all the columns
R1[:,-1]=R1.sum(axis=1)
print(R1)

[[ 16  17  14 118]
 [ 20  27  14 151]
 [ 21  23  20 156]]


In [64]:
#create a matrix (3x4) R1 of random numbers between 10-40
R1=np.random.randint(10,40,(3,4))
print(R1)

[[20 30 39 32]
 [11 39 34 31]
 [19 24 28 14]]


In [86]:
#replace all even elements with nan in R1
R2=R1[:,:].astype("float")
print(R2)
idx=R2%2==0
print(idx)
R2[idx]=np.nan
print(R2)
#count number of nan in R1
nan_R2 = np.isnan(R2) #give true and false
print()
print(nan_R2.sum())
print()
print(nan_R2)
print(np.count_nonzero(nan_R2))

[[20. 30. 39. 32.]
 [11. 39. 34. 31.]
 [19. 24. 28. 14.]]
[[ True  True False  True]
 [False False  True False]
 [False  True  True  True]]
[[nan nan 39. nan]
 [11. 39. nan 31.]
 [19. nan nan nan]]

7

[[ True  True False  True]
 [False False  True False]
 [False  True  True  True]]
7


In [84]:
help(np.count_nonzero)

Help on function count_nonzero in module numpy:

count_nonzero(a, axis=None)
    Counts the number of non-zero values in the array ``a``.
    
    The word "non-zero" is in reference to the Python 2.x
    built-in method ``__nonzero__()`` (renamed ``__bool__()``
    in Python 3.x) of Python objects that tests an object's
    "truthfulness". For example, any number is considered
    truthful if it is nonzero, whereas any string is considered
    truthful if it is not the empty string. Thus, this function
    (recursively) counts how many elements in ``a`` (and in
    sub-arrays thereof) have their ``__nonzero__()`` or ``__bool__()``
    method evaluated to ``True``.
    
    Parameters
    ----------
    a : array_like
        The array for which to count non-zeros.
    axis : int or tuple, optional
        Axis or tuple of axes along which to count non-zeros.
        Default is None, meaning that non-zeros will be counted
        along a flattened version of ``a``.
    
        .. vers

In [87]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)


[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
